### ISSUE TITLE
The Hive Dockerfile(s) incorrectly symlink the Postgresql JDBC Driver Path

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/hive#54]
The Hive images use the Hadoop ones as the base image, and in doing so symbolically link the various jdbc drivers (i.e. mysql and postgresql) we're interested in into paths in the container that we have configured Hive to use. In this case, `$HIVE_HOME` is set to /opt/hive in the container.

The problem, however, is that we're symbolically linking the directory that contains this Postgresql JAR file, and not the actual file itself. This results in beeline/hive/etc. using whatever Postgresql jar is stored in /opt/hive/lib and not the nested /opt/hive/lib/postgresql-jdbc.jar/postgresql-42.2.16.jar that we expect those clients would use.

To verify and/or experiment, you could transfer a newer JDBC driver into the /tmp/ directory in the Hive server Pod (to avoid permissions errors with Openshift pods security policies) and then symbolically link the newer JDBC driver located in the /tmp/ directory to `$HIVE_HOME/lib/postgresql-<verison>.jar`, and then firing up beeline. Beeline should report the driver version in it's initialization logs, so it's a quick verification.

**Comment by EmilyM1** [comment]
So from here it's a mod on the existing Dockerfile to use the correct jar location of opt/hive/lib and also fixing the symlink, that is needed to get this working? Anything else?

**Comment by EmilyM1** [comment]
Hey @timflannagan1  I am in /opt/hive/lib right now and I see 

-rw-r--r--. 1 hadoop root  1002883 Oct 21 20:21 postgresql-42.2.16.jar
-rwxrwxr--. 1   1002 root   645268 Oct  8 22:58 postgresql-9.4.1208.jre7.jar
lrwxrwxrwx. 1   1002 root       35 Oct  9 20:26 postgresql-jdbc.jar -> /usr/share/java/postgresql-jdbc.jar
-rwxrwxr--. 1   1002 root     8300 Oct  8 22:58 postgresql-metadata-storage-0.9.2.jar

Since I put the 42.22.16 jar in I am going to remove the 
-rwxrwxr--. 1   1002 root   645268 Oct  8 22:58 postgresql-9.4.1208.jre7.jar
lrwxrwxrwx. 1   1002 root       35 Oct  9 20:26 postgresql-jdbc.jar -> /usr/share/java/postgresql-jdbc.jar

they are not needed.
However, what is this one
-rwxrwxr--. 1   1002 root     8300 Oct  8 22:58 postgresql-metadata-storage-0.9.2.jar?
